# Generated by Django 5.2 on 2025-04-24 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLAN', 'Planning'), ('ACTIVE', 'Active'), ('HOLD', 'On Hold'), ('COMP', 'Completed')], default='PLAN', max_length=10)),
                ('build_address_line1', models.CharField(blank=True, max_length=255)),
                ('build_address_line2', models.CharField(blank=True, max_length=255)),
                ('build_city', models.CharField(blank=True, max_length=100)),
                ('build_state', models.CharField(blank=True, max_length=50)),
                ('build_zip_code', models.CharField(blank=True, max_length=20)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='LehmanCustomConstruction.customer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_added'],
            },
        ),
    ]
