# Generated by Django 5.2 on 2025-04-24 20:16

import LehmanCustomConstruction.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0005_customerdocument_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='LehmanCustomConstruction.customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('WARRANTY', 'Warranty'), ('PLAN', 'Plan/Blueprint'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=LehmanCustomConstruction.models.get_document_upload_path),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='LehmanCustomConstruction.project'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='original_filename',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
