# Generated by Django 5.2 on 2025-04-25 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0006_customerdocument_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='LehmanCustomConstruction.expensecategory', verbose_name='Expense Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='LehmanCustomConstruction.project')),
            ],
            options={
                'verbose_name': 'Budget Line Item',
                'verbose_name_plural': 'Budget Line Items',
                'ordering': ['project', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'category'), name='unique_project_category_budget')],
            },
        ),
    ]
