# Generated by Django 5.2 on 2025-04-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0008_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary of the post, used in list views. Optional.'),
        ),
    ]
