# Generated by Django 5.2 on 2025-04-27 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0011_customer_is_active_project_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='customerdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Customer Documents'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RenameField(
            model_name='budgetlineitem',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='budgetlineitem',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='contactinquiry',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_added',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for portfolio grid.', null=True, upload_to='portfolio/featured/'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for project page.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible on public portfolio page?'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for portfolio grid.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name. Auto-generated if blank.', max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name. Auto-generated if blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary for list views.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional featured image.', null=True, upload_to='blog_featured_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text="Set date to make post live (if status='Published').", null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name. Auto-generated if blank.', max_length=270, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='LehmanCustomConstruction.customer'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='LehmanCustomConstruction.project'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='LehmanCustomConstruction.portfoliocategory', verbose_name='Portfolio Category'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='LehmanCustomConstruction.project')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
