# Generated by Django 5.2 on 2025-04-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0012_portfoliocategory_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name. Auto-generated if blank.', max_length=270, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the portfolio grid.', null=True, upload_to='portfolio_featured_images/')),
                ('short_description', models.TextField(blank=True, help_text='A brief description displayed under the image in the grid.')),
                ('details', models.TextField(help_text='Detailed information about the project.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='LehmanCustomConstruction.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the image in the gallery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='LehmanCustomConstruction.portfolioproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
