# Generated by Django 5.2 on 2025-04-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0013_portfolioproject_portfolioimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['order', 'uploaded_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Internal reference image.', null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, help_text='Internal detailed description.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Obsolete? Use PortfolioProject model for public visibility.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_projects', to='LehmanCustomConstruction.portfoliocategory', verbose_name='Portfolio Category (Internal Use)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Internal brief description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_images', to='LehmanCustomConstruction.project'),
        ),
    ]
