# Generated by Django 5.2 on 2025-04-28 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0014_alter_portfolioimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='customerdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Customer Document', 'verbose_name_plural': 'Customer Documents'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio Category', 'verbose_name_plural': 'Portfolio Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Portfolio Gallery Image', 'verbose_name_plural': 'Portfolio Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project (Internal)', 'verbose_name_plural': 'Projects (Internal)'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Internal Project Image', 'verbose_name_plural': 'Internal Project Images'},
        ),
        migrations.AddField(
            model_name='expense',
            name='draw_number',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Draw 1'), (2, 'Draw 2'), (3, 'Draw 3')], db_index=True, help_text='Which draw period does this expense belong to?', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Set date to make post live (if status='Published').", null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLAN', 'Planning'), ('ACTIVE', 'Active'), ('HOLD', 'On Hold'), ('COMP', 'Completed')], db_index=True, default='PLAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Specific item description (e.g., 'labor for framing', 'Permit Fee')", max_length=255)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='LehmanCustomConstruction.expensecategory', verbose_name='Expense Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='LehmanCustomConstruction.project')),
            ],
            options={
                'verbose_name': 'Cost Item (Budget Line)',
                'verbose_name_plural': 'Cost Items (Budget Lines)',
                'ordering': ['project', 'category__name', 'description'],
            },
        ),
        migrations.DeleteModel(
            name='BudgetLineItem',
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.UniqueConstraint(fields=('project', 'category', 'description'), name='unique_project_category_item_budget'),
        ),
    ]
