# Generated by Django 5.2 on 2025-04-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0015_alter_blogcategory_options_alter_blogpost_options_and_more'),
        ('LehmanCustomConstruction', '0016_seed_expense_categories'),
    ]

    operations = [
    ]
