# Generated by Django 5.2 on 2025-04-30 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0017_merge_20250428_1617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_document',
            field=models.ForeignKey(blank=True, help_text='Link to an uploaded document/receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='LehmanCustomConstruction.customerdocument'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note_type', models.CharField(choices=[('NOTE', 'General Note'), ('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('SITE', 'Site Visit'), ('UPDATE', 'Project Update')], default='NOTE', max_length=10)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='LehmanCustomConstruction.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='LehmanCustomConstruction.project')),
            ],
            options={
                'verbose_name': 'Activity Log / Note',
                'verbose_name_plural': 'Activity Logs / Notes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
