# Generated by Django 5.2 on 2025-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0018_alter_customerdocument_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitem',
            name='description',
            field=models.CharField(help_text="Specific item description (e.g., 'labor for framing', 'Permit Fee') - From QBO Estimate", max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image (e.g., room name).', max_length=255),
        ),
    ]
