# Generated by Django 5.2 on 2025-05-02 17:04

import LehmanCustomConstruction.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0019_alter_costitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_featured_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=270, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption (e.g., room name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to=LehmanCustomConstruction.models.get_portfolio_image_upload_path),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=270, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_projects', to='LehmanCustomConstruction.portfoliocategory', verbose_name='Portfolio Category (Optional Internal)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images_internal/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
