# Generated by Django 5.2 on 2025-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0020_remove_project_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
