# Generated by Django 5.2 on 2025-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehmanCustomConstruction', '0021_portfoliocategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['portfolio_project', 'order', 'uploaded_at'], 'verbose_name': 'Portfolio Gallery Image', 'verbose_name_plural': 'Portfolio Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Project', 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., City, State or Neighborhood', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display on portfolio list pages (lower numbers show first).'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate square footage.', null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('COMING_SOON', 'Coming Soon'), ('DESIGN_PHASE', 'Design Phase')], default='COMPLETED', help_text='Current status of this portfolio project (for display).', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='year_completed',
            field=models.PositiveIntegerField(blank=True, help_text='Year the project was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of image in the gallery (lower numbers show first).'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='details',
            field=models.TextField(help_text="Detailed information about the project, shown on the project's detail page."),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the portfolio grid and hero.', null=True, upload_to='portfolio_featured_images/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls if this project is visible on the public site.'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief description displayed on portfolio list pages.'),
        ),
    ]
